# This is part of a GNU Makefile, to specify system-dependent
# parts of the Makefile enviroment.
#
# This gets included as part of the GNU Makefile used in each of
# the subdirectories.
#
# Depending on your platform, you need to select the correct definition.
# Also, you need to edit the Makefile in the bin subdirectory.


# Operating system settings.

HOST = -DHOST_LINUX
CXX  = g++
LD   = g++
CPP  = gcc


# Platform settings.

ARCHITECTURE := $(shell uname -m)
ifeq "$(ARCHITECTURE)" 'i686'
    HOST += -DHOST_i386
else ifeq "$(ARCHITECTURE)" 'i586'
    HOST += -DHOST_i386
else ifeq "$(ARCHITECTURE)" 'i486'
    HOST += -DHOST_i386
else ifeq "$(ARCHITECTURE)" 'x86_64'
    HOST += -DHOST_$(ARCHITECTURE)
else ifneq "$(ARCHITECTURE)" 'i386'
    $(error Unsupported architecture: $(ARCHITECTURE))
endif

# In case a big-endian processor is needed:
#HOST += -DHOST_IS_BIG_ENDIAN
