.PHONY: all clean depend

all: $(PROGRAM)

clean:
	@echo ":: Cleaning $$(tput bold)$(notdir $(CURDIR))$$(tput sgr0)"
	@$(RM) $(PROGRAM) $(OBJ_FILES)

depend: $(SRC_FILES) $(HDR_FILES)
	@echo ':: Generating dependencies'
    # WARNING: this may break if the preprocessor outputs something, because
    # that would get mixed with the dependency output.
	@$(CC) $(INCLUDE_DIRS) $(DEFINES) $(HOST) -MM $^ >Makefile.depends

$(PROGRAM): $(OBJ_FILES)
	@echo ":: Linking $$(tput bold)$@$$(tput sgr0)"
	@$(LD) $^ $(LDFLAGS) -o $@

# Usage of `patsubst` is a hack that should be removed later.  The problem
# is that `make depend` generates duplicate rules with different
# dependencies, and it seems that different versions of GNU Make follow
# different orders.
$(OBJ_FILES): %.o:
	@echo ":: Compiling $$(tput bold)$@$$(tput sgr0)"
	@$(CXX) $(CXXFLAGS) -c $(patsubst %.hh,%.cc,$<)
